### ISSUE TITLE
Fill textareas with URL's GET parameters

### ISSUE THREAD

**Issue by xem** [xem/miniCodeEditor#10]
@p01 @subzey @aemkei 

Do you think MiniCodeEditor could read the URL, like:

```
...?html=(urlencoded text)&css=(urlencoded text)&js=(urlencoded text)
```

And fill the textareas with the urldecoded values when the page loads,

And still fit in 256b ?

I say, challenge accepted.

**Comment by rlauck** [comment]
If you always provide the uri params, and they are always in order of js, css, html... heres a version in 227 bytes, although it does not automatically evaluate on page load - probably need to stash the oninput code in a named function and call it after the loop.

```
<x id=e><script>for(i=3,q=location.href.split(/[?&]\w+=/g);i;)e.innerHTML+='<textarea id=t'+i+' oninput=\'e.lastChild.srcdoc=t3[v="value"]+"<script>"+t1[v]+"<\/script><style>"+t2[v]\'rows=9>'+unescape([q[i--]])</script><iframe>
```

**Comment by xem** [comment]
Nice!

I added execution on load, by triggering an input event, but it takes too many bytes (273). I'll try to use a function instead.

```
<body id=e onload='t1.dispatchEvent(Event("input"))'><script>for(i=3,q=location.href.split(/[?&]\w+=/g);i;)e.innerHTML+='<textarea id=t'+i+' oninput=\'e.lastChild.srcdoc=t3[v="value"]+"<script>"+t1[v]+"<\/script><style>"+t2[v]\'rows=9>'+unescape([q[i--]]);</script><iframe>
```

**Comment by xem** [comment]
I think I nailed it : 249 bytes!

So, put that in get.html:

```
<body id=e onload=d()><script>function d(){e.lastChild.srcdoc=t3[v="value"]+"<script>"+t1[v]+"<\/script><style>"+t2[v]}for(i=3;i;)e.innerHTML+='<textarea id=t'+i+' oninput=d() rows=9>'+unescape(location.href.split(/[?&]\w+=/g)[i--])</script><iframe>
```

and visit

```
get.html?a=alert(1)&b=*{color:red&c=html
```

Does it work for you too?

=D

**Comment by xem** [comment]
It also works for me if I don't provide a parametric URL

```
get.html
```

cc/ @rlauck @p01 @subzey @aemkei

**Comment by xem** [comment]
Please look at modern-params.html and cross-browser-params.html

**Comment by rlauck** [comment]
Nice! Think there is enough room left for localStorage too?

**Comment by xem** [comment]
I'm working on a thing that updates the url on each input. I think it's more useful than localStorage, isn't it?
But we can add localStorage persistance too, why not! If we have an editor + readable/writable URL + localstorage + CSS in less than 512 bytes, that would be nice!
