### ISSUE TITLE
On load, fill textareas from the URL. On input, update URL.

### ISSUE THREAD

**Issue by xem** [xem/miniCodeEditor#11]
Hi @rlauck @p01 @aemkei  @subzey,

Here's my new challenge: code golfing modern-param.html.

As we saw in #10, reading textarea's values from URL is possible in 256bytes, but this time, I also want the URL to be updated on each input. (on browsers supporting it)

That's what I made (with rlauck's help) in modern-param.html

http://xem.github.io/miniCodeEditor/modern-param.html <= empty

http://xem.github.io/miniCodeEditor/modern-param.html?j=/*%20JS%20*/&c=*%20{%0A%20%20color%3A%20red%0A}&h=HTML%0ACode%0A <= filled

(type text) <= URL is updated

So, can you beat my 347 bytes? :D

**Comment by xem** [comment]
=> 323 bytes now!

http://xem.github.io/miniCodeEditor/modern-param.html?j=/*%20JS%20*/%0Adocument.body.innerHTML%20+%3D%20%22%20bytes!%22&c=*%20{%0A%20%20color%3A%20blue%0A}&h=MiniCodeEditor%0A%3Cbr%3E%0Awith%20URL%20save%20%26amp%3B%20load%20in%20%3Cb%3E323%3C/b%3E%0A

**Comment by rlauck** [comment]
comma separating is a great idea! What do you think about using location.hash instead of history.replaceState?

**Comment by xem** [comment]
Sure, all possible solutions are ok for me, as long as we don't lose the save/load feature and the current browser support (Chrome, opera 15, Firefox)

Also @subzey made it 16 bytes shorter a few hours ago.

**Comment by xem** [comment]
done in 254 bytes ;)
So I close this issue
