### ISSUE TITLE
miniCodeEditor customizer

### ISSUE THREAD

**Issue by xem** [xem/miniCodeEditor#12]
Here's the idea (suggestions are welcome):
# Source code

[ (textarea with the code) ]
Bytes counter - Download link

**Version**

[ ] minimal (175 bytes)
[ ] shareable (< 256 bytes)
[ ] shareable + cross-browser + placeholders (< 350 bytes)

**Style**

[x] none
[ ] fullscreen, screen divided in 4 equal parts (+ 155 bytes)
[ ] fullscreen, textareas on top (+ 197 bytes)
[ ] fullscreen, textareas on left (+ 244 bytes)

**Comment by subzey** [comment]
They say in Russian, "wealth of choice leads to no good".

I don't think such highly customizable setup would be actually needed. As for me, it's better to pick certain use cases:
- _modern_, as an example of smallest possible jsfiddle-like code ("the Demo");
- _cross-browser with placeholders and load via url_, as a fully-functional tool for quick cross-browser tests and small code exchange, possibly right on github.io ("the Production").

Splitting code into separate sections would make the golfing harder and may possibly prevent some golfing tricks. But, it's all up to you.

**Comment by xem** [comment]
Russian philosophy is good.
You're right, I think I'm gonna highlight two versions as you suggest,
And add a little option to append one of the three optional styles in the source code textarea.
So we will just maintain 2 HTML files (+3 css files), with their unique url.

What do you mean by "right on github.io" ? something like miniCodeEditor.github.io ?
I can also consider buying a domain name...

**Comment by subzey** [comment]
Less editing and more fun. That sounds great for me!

Sorry for misleading sentence, saying "right on github.io", I didn't mean that domain name should be changed, I meant just the fact code can be shared, something like [this](http://xem.github.io/miniCodeEditor/modern-url.html#Zm9vLmlubmVySFRNTD1mb28uaW5uZXJIVE1MLnJlcGxhY2UoL1xibWNlXGIvZ2ksJzxzdHJvbmc+JCY8L3N0cm9uZz4nKQ==,Ym9keSB7dGV4dC1hbGlnbjpjZW50ZXJ9,PHAgaWQ9ImZvbyI+SSBhbSB1c2luZyBtQ0UgZm9yIHNoYXJpbmcgY29kZSE8L3A+).

**Comment by xem** [comment]
Oh, sure. I'll do that. Thanks for your input!

**Comment by xem** [comment]
Ok, it's done, please check the homepage and suggest enhancements if something's bad :)

**Comment by xem** [comment]
I followed your advice and cleaned the homepage.
Next thing to do: add new features in the full version, like:
- make non-ascii chars shareable
- allow to use tabulations
- keep the browser's history clean
- Syntax highlight?
- <a href=http://xem.github.io/miniMinifier>minification</a>?
- Other ideas?

**Comment by subzey** [comment]
All these are great, but miniCodeEditor would become codeEditor ;)

**Comment by xem** [comment]
You're right :)

I don't want mCE to be an endless collection of features either, I think I'll stop at 1k.

So I think I'll just make the three first features listed above + fix the old IE compatibility, because I think it's a real plus compared to JSFiddle/Codepen/etc that don't work on IE and many people asked for tabs and clean history.

Then I'll stop :p 

...

Oh, I will also try to make a better tweetable version (@subzey, did you see my improvement on our 140bytes JS executer? https://gist.github.com/xem/7086007) I'll try to use that.
