### ISSUE TITLE
Enhancement: make back button useful

### ISSUE THREAD

**Issue by jelmerdemaat** [xem/miniCodeEditor#13]
Great project, I like it!

An idea for improvement: the back button is kinda useless now. It goes back to previously generated URLs (of which there are quite a lot) but doesn't change content.
Maybe the back button can be pointed at the page the visitor came from?

**Comment by xem** [comment]
Sure,
I'm working on it! (there's a similar issue on my other project: https://github.com/xem/paste/issues/2)
Thanks for your suggestion!

**Comment by jelmerdemaat** [comment]
Great! :thumbsup:

**Comment by xem** [comment]
done (except on IE that can't handle it)
