### ISSUE TITLE
replace the iframe with a DIV or a  P or... the body?

### ISSUE THREAD

**Issue by xem** [xem/miniCodeEditor#14]
@subzey, @rlauck

After all, why do we keep an iframe for rendering?

I believe that a div, a p (or any container) can also contain any HTML + a style tag + a script tag.

And why not directly update the body? The one  that contains the three textareas...

I think the only drawback of this approach would be the global vars introduced by miniCodeEditor that can interfere with the vars created by the user... (but I think we can fix that)

Anyway, this could save us some bytes... let s try...?

**Comment by xem** [comment]
So I made this in 149 bytes.

It's quite dirty, though:

```
<body oninput='e[I]=t3[v="value"]+"<style>"+t2[v];eval(t1[v])'onload='for(i=4;i--;)b[I="innerHTML"]+=i?"<textarea id=t"+i+" rows=9>":"<x id=e>"'id=b>
```

But it works.

On ALL browsers!

![149](https://f.cloud.github.com/assets/1225909/1733266/b12909b8-6334-11e3-8c7b-104b6e9c89d8.png)

What do you think?...

**Comment by xem** [comment]
cc/ @aemkey and @p01

**Comment by p01** [comment]
No no no. The IFRAME ( or OBJECT if you want ) MUST stay.

Without an IFRAME or similar, the script, style, events, everything leaks all over the place and the code does not behave as it would as a standalone document. For instance you can style and hide the TEXTAREAs, the X element, ... you can't listen to the onload event or domContentLoaded event, etc... the DOM tree is completely different, ...

**Comment by aemkei** [comment]
At usually I would vote for reduced code, but I agree with @p01: Do NOT skip the `iframe` because otherwise we loose our independent sandbox.

**Comment by xem** [comment]
I agree too =) the drawbacks are too important.
But it was fun to try anyway.
Thanks

**Comment by xem** [comment]
updating the "upper" body instead of the iframe would also have too many inconvénients. right?
