### ISSUE TITLE
It can fit in 32 bytes...

### ISSUE THREAD

**Issue by xem** [xem/miniCodeEditor#15]
Well, technically, any web app can fit in 32 bytes. So miniCodeEditor too.

@bburky and I made an URL-based arbitrary code executer in 32 bytes, and used it on miniCodeEditor:

<a href="http://xem.github.io/32b/#';document.write(unescape(atob('JTNDeCUyMGlkJTNEZSUzRSUzQ3NjcmlwdCUzRWZvciUyOGklM0QzJTNCaS0tJTNCJTI5ZS5pbm5lckhUTUwrJTNEJTI3JTNDdGV4dGFyZWElMjBpZCUzRHQlMjcraSslMjclMjBvbmlucHV0JTNEJTVDJTI3ZS5sYXN0Q2hpbGQuc3JjZG9jJTNEdDIlNUJ2JTNEJTIydmFsdWUlMjIlNUQrJTIyJTNDc2NyaXB0JTNFJTIyK3QwJTVCdiU1RCslMjIlM0MlNUMvc2NyaXB0JTNFJTNDc3R5bGUlM0UlMjIrdDElNUJ2JTVEJTVDJTI3cm93cyUzRDklM0UlMjclM0Mvc2NyaXB0JTNFJTNDaWZyYW1lJTNF')));location.hash=''">look at that!</a>

So @aemkei @p01 & @subzey, should we consider this valid, or cheat?

More info here: http://github.com/xem/32b

**Comment by subzey** [comment]
Data-URL fits anything in 0 bytes, hehe.

**Comment by xem** [comment]
Yeah, I just remember that while discussing with bburky: https://github.com/xem/32b/issues/1#issuecomment-30600274

Ok, never mind =D
