### ISSUE TITLE
URL Shorteners?

### ISSUE THREAD

**Issue by bburky** [xem/miniCodeEditor#17]
URL shorteners would be a logical extension to either paste or miniCodeEditor. It also makes large documents easily tweetable.

You could probably steal some code from a URL shortener bookmarklet to implement this. You would want to choose whichever URL shortener allows the longest URLs. 

Basically, you can use a URL shortener as a backend database.

http://tinyurl.com/noha39u

**Comment by xem** [comment]
Hey, you know what? I already made my own (revolutionnary) URL shortener a few years ago.
I'll try to re-put it online this evening.
Thanks for the idea!

**Comment by xem** [comment]
mmm...
it's not that simple to send the url to an url shortener, because the hash (#...) is stripped by the browser when it makes a request to a server...

**Comment by xem** [comment]
So, url shorteners are great but finally I won't include / impose an url shortener in mCE, because mCE's URLs work without it, and when we pastelong URLs on twitter (and others maybe) they are automatically shortened.
