### ISSUE TITLE
Saving bytes in the iframe's update function

### ISSUE THREAD

**Issue by xem** [xem/miniCodeEditor#6]
@aemkei @p01 @subzey 
Currently, the iframe is updated with this code:

```
t0.src="data:text/html;base64,"+btoa(...
```

On #1, p01 suggests to use escape(), but worries about special chars
https://github.com/xem/miniCodeEditor/pull/1#issuecomment-29972623

```
t0.innerHTML=escape(...
```

On hacker news, a guy suggests to use srcdoc:
https://news.ycombinator.com/item?id=6864700

```
t0.srcdoc=...
```

Which solution do you prefer?

And which characters could break it? (if at least all the "extended ascii" chars work, I'm fine with it.)

**Comment by xem** [comment]
Hmm... srcdoc seems to work perfectly, but only on Firefox... IE and chrome don't update the iframe...
Weird: Chrome says it supports srcdoc since version 4
Both IE and Chrome don't throw an error...

**Comment by xem** [comment]
Update: srcdoc works fine on chrome as an attribute, but nothing happens if I try to set it with JS:

```
<textarea onkeyup="f.srcdoc='plop'"></textarea>
<iframe id=f></iframe>
=> ko
```

...

```
<iframe id=f></iframe>
<script>'f.srcdoc="plop"'</script>
=> ko
```

**Comment by xem** [comment]
Update: I found why:
On firefox, t0 === the iframe element
On chrome and IE, t0 === the iframe's window object
srcdoc only works on the element...
So i'll re-use e.lastChild :)

**Comment by xem** [comment]
Well, sorry for the monolog, I sorted it out, and tested it thoroughly, it's perfect.
Updated the homepage to highlight the new bytes count: 185+
http://xem.github.io/miniCodeEditor/

**Comment by bburky** [comment]
Cool. Thanks for using my suggestion. The only thing to note about `srcdoc` is that when using it in HTML source (not setting it via javascript attributes) you must escape quotes as HTML entities. But you don't need that at all when using javascript, so it works great.

**Comment by xem** [comment]
yeah. thanks to you! :)
