### ISSUE TITLE
Quote attribute values

### ISSUE THREAD

**Issue by zlatanvasovic** [xem/miniCodeEditor#7]
You must quote attribute values, because of XSS.

``` html
<!-- bad -->
<x id=e></x>

<!-- good -->
<x id="e"></x>
```

**Comment by xem** [comment]
Can you please precise what kind of xss attack can happen with 

```
  <x id=e>
```

?

**Comment by zlatanvasovic** [comment]
http://mathiasbynens.be/notes/unquoted-attribute-values

2013/12/7 xem notifications@github.com

> Can you please precise what kind of xss attack can happen with ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/xem/miniCodeEditor/issues/7#issuecomment-30052643
> .

## 

Zlatan Vasović - _ZDroid_

**Comment by xem** [comment]
Great article! However I don't think any XSS attack can happen in miniCodeEditor, because of the unquoted attributes...

Moreover, the app's purpose is to use user input directly to update an iframe, so the XSS risk would rather be there, not in the attributes... don't you think?

**Comment by zlatanvasovic** [comment]
I know, but whenever you can change id value and then remove default
styles. I think that quotes are ok for id attribute.

2013/12/7 xem notifications@github.com

> Great article! However I don't think any XSS attack can happen in
> miniCodeEditor, because of the unquoted attributes...
> 
> Moreover, the app's purpose is to use user input directly to update an
> iframe, so the XSS risk would rather be there, not in the attributes...
> don't you think?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/xem/miniCodeEditor/issues/7#issuecomment-30054518
> .

## 

Zlatan Vasović - _ZDroid_

**Comment by xem** [comment]
Well, I close this issue since there doesn't seem to be a real risk...
Thanks anyway for the infos!
